# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "ğŸ  Home" #About me
    url: '#about'
    weight: 10
  - name: "âœ Posts"
    url: '#posts'
    weight: 20
  - name: "ğŸ“š Tutorials"
    url: '#projects'
    weight: 30
#  - name: Talks
#    url: '#talks'
#    weight: 40
  - name: "ğŸ–Š Publications"
    #url: '#featured'
    url: '#publications'
    weight: 50
  #- name: Courses
  #  url: courses/
  #  weight: 60
  - name: "ğŸ–¼ï¸ Gallery"
    url: '#gallery'
    weight: 70
  - name: "â˜ Contact"
    url: '#contact'
    weight: 80
